insert into marvel_character(id, character_name, affinity) values(1001,'Captain America','Combat');
insert into marvel_character(id, character_name, affinity) values(1002,'Absorbing Man','Combat');
insert into marvel_character(id, character_name, affinity) values(1003,'Agent Venom','Combat');
insert into marvel_character(id, character_name, affinity) values(1004,'America Chavez','Combat');
insert into marvel_character(id, character_name, affinity) values(1005,'Apocalypse','Combat');
insert into marvel_character(id, character_name, affinity) values(1006,'Beast','Combat');
insert into marvel_character(id, character_name, affinity) values(1007,'Black Panther','Combat');
insert into marvel_character(id, character_name, affinity) values(1008,'Blade','Combat');
insert into marvel_character(id, character_name, affinity) values(1009,'Bullseye','Combat');
insert into marvel_character(id, character_name, affinity) values(1010,'Carnage','Combat');
insert into marvel_character(id, character_name, affinity) values(1011,'Colossus','Combat');
insert into marvel_character(id, character_name, affinity) values(1012,'Crescent','Combat');
insert into marvel_character(id, character_name, affinity) values(1013,'Crossbones','Combat');
insert into marvel_character(id, character_name, affinity) values(1014,'Deathlok','Combat');
insert into marvel_character(id, character_name, affinity) values(1015,'Doctor Octopus','Combat');
insert into marvel_character(id, character_name, affinity) values(1016,'Drax','Combat');
insert into marvel_character(id, character_name, affinity) values(1017,'Giant-Man','Combat');
insert into marvel_character(id, character_name, affinity) values(1018,'Goliath','Combat');
insert into marvel_character(id, character_name, affinity) values(1019,'Gorgon','Combat');
insert into marvel_character(id, character_name, affinity) values(1020,'Gorilla-Man','Combat');
insert into marvel_character(id, character_name, affinity) values(1021,'Groot','Combat');
insert into marvel_character(id, character_name, affinity) values(1022,'Hogun','Combat');
insert into marvel_character(id, character_name, affinity) values(1023,'Hulk','Combat');
insert into marvel_character(id, character_name, affinity) values(1024,'Hulkling','Combat');
insert into marvel_character(id, character_name, affinity) values(1025,'Iron Fist','Combat');
insert into marvel_character(id, character_name, affinity) values(1026,'Iron Man Mark 44 (Hulkbuster)','Combat');
insert into marvel_character(id, character_name, affinity) values(1027,'Jessica Jones','Combat');
insert into marvel_character(id, character_name, affinity) values(1028,'Juggernaut','Combat');
insert into marvel_character(id, character_name, affinity) values(1029,'Killmonger','Combat');
insert into marvel_character(id, character_name, affinity) values(1030,'Kingpin','Combat');
insert into marvel_character(id, character_name, affinity) values(1031,'Lizard','Combat');
insert into marvel_character(id, character_name, affinity) values(1032,'Luke Cage','Combat');
insert into marvel_character(id, character_name, affinity) values(1033,'Minn-Erva','Combat');
insert into marvel_character(id, character_name, affinity) values(1034,'Molten Man','Combat');
insert into marvel_character(id, character_name, affinity) values(1035,'Moon Knight','Combat');
insert into marvel_character(id, character_name, affinity) values(1036,'Mister Fantastic','Combat');
insert into marvel_character(id, character_name, affinity) values(1037,'Ms. Marvel (Kamala Khan)','Combat');
insert into marvel_character(id, character_name, affinity) values(1038,'Namor','Combat');
insert into marvel_character(id, character_name, affinity) values(1039,'Nebula','Combat');
insert into marvel_character(id, character_name, affinity) values(1040,'Punisher','Combat');
insert into marvel_character(id, character_name, affinity) values(1041,'Red Hulk','Combat');
insert into marvel_character(id, character_name, affinity) values(1042,'Rhino','Combat');
insert into marvel_character(id, character_name, affinity) values(1043,'Sabretooth','Combat');
insert into marvel_character(id, character_name, affinity) values(1044,'Sandman','Combat');
insert into marvel_character(id, character_name, affinity) values(1045,'Shang-Chi','Combat');
insert into marvel_character(id, character_name, affinity) values(1046,'She-Hulk','Combat');
insert into marvel_character(id, character_name, affinity) values(1047,'Sif','Combat');
insert into marvel_character(id, character_name, affinity) values(1048,'Skurge','Combat');
insert into marvel_character(id, character_name, affinity) values(1049,'Sword Master','Combat');
insert into marvel_character(id, character_name, affinity) values(1050,'Taskmaster','Combat');
insert into marvel_character(id, character_name, affinity) values(1051,'Thing','Combat');
insert into marvel_character(id, character_name, affinity) values(1052,'Titania','Combat');
insert into marvel_character(id, character_name, affinity) values(1053,'Ulik','Combat');
insert into marvel_character(id, character_name, affinity) values(1054,'Valkyrie','Combat');
insert into marvel_character(id, character_name, affinity) values(1055,'Venom','Combat');
insert into marvel_character(id, character_name, affinity) values(1056,'Volstagg','Combat');
insert into marvel_character(id, character_name, affinity) values(1057,'War Tiger','Combat');
insert into marvel_character(id, character_name, affinity) values(1058,'Warpath','Combat');
insert into marvel_character(id, character_name, affinity) values(1059,'Warwolf','Combat');
insert into marvel_character(id, character_name, affinity) values(1060,'White Tiger','Combat');
insert into marvel_character(id, character_name, affinity) values(1061,'Wolverine','Combat');
insert into marvel_character(id, character_name, affinity) values(1062,'Adam Warlock','Blast');
insert into marvel_character(id, character_name, affinity) values(1063,'Ancient One','Blast');
insert into marvel_character(id, character_name, affinity) values(1064,'Baron Mordo','Blast');
insert into marvel_character(id, character_name, affinity) values(1065,'Bisop','Blast');
insert into marvel_character(id, character_name, affinity) values(1066,'Blue Dragon','Blast');
insert into marvel_character(id, character_name, affinity) values(1067,'Cable','Blast');
insert into marvel_character(id, character_name, affinity) values(1068,'Captain America (Sharon Rogers)','Blast');
insert into marvel_character(id, character_name, affinity) values(1069,'Crystal','Blast');
insert into marvel_character(id, character_name, affinity) values(1070,'Cyclops','Blast');
insert into marvel_character(id, character_name, affinity) values(1071,'Daisy Johnson','Blast');
insert into marvel_character(id, character_name, affinity) values(1072,'Doctor Strange','Blast');
insert into marvel_character(id, character_name, affinity) values(1073,'Emma Frost','Blast');
insert into marvel_character(id, character_name, affinity) values(1074,'Enchantress','Blast');
insert into marvel_character(id, character_name, affinity) values(1075,'Gambit','Blast');
insert into marvel_character(id, character_name, affinity) values(1076,'Human Torch','Blast');
insert into marvel_character(id, character_name, affinity) values(1077,'Hydro-Man','Blast');
insert into marvel_character(id, character_name, affinity) values(1078,'Iceman','Blast');
insert into marvel_character(id, character_name, affinity) values(1079,'Inferno','Blast');
insert into marvel_character(id, character_name, affinity) values(1080,'Invisible Woman','Blast');
insert into marvel_character(id, character_name, affinity) values(1081,'Iron Man','Blast');
insert into marvel_character(id, character_name, affinity) values(1082,'Ironheart','Blast');
insert into marvel_character(id, character_name, affinity) values(1083,'Jean Grey','Blast');
insert into marvel_character(id, character_name, affinity) values(1084,'Jubilee','Blast');
insert into marvel_character(id, character_name, affinity) values(1085,'Kaecilius','Blast');
insert into marvel_character(id, character_name, affinity) values(1086,'Kid Omega','Blast');
insert into marvel_character(id, character_name, affinity) values(1087,'Lash','Blast');
insert into marvel_character(id, character_name, affinity) values(1088,'Lincoln Campbell','Blast');
insert into marvel_character(id, character_name, affinity) values(1089,'M.O.D.O.K.','Blast');
insert into marvel_character(id, character_name, affinity) values(1090,'Magik','Blast');
insert into marvel_character(id, character_name, affinity) values(1091,'Magneto','Blast');
insert into marvel_character(id, character_name, affinity) values(1092,'Malekith','Blast');
insert into marvel_character(id, character_name, affinity) values(1093,'Mantis','Blast');
insert into marvel_character(id, character_name, affinity) values(1094,'Maximus','Blast');
insert into marvel_character(id, character_name, affinity) values(1095,'Mister Sinister','Blast');
insert into marvel_character(id, character_name, affinity) values(1096,'Moon Girl','Blast');
insert into marvel_character(id, character_name, affinity) values(1097,'Mysterio','Blast');
insert into marvel_character(id, character_name, affinity) values(1098,'Negasonic Teenage Warhead','Blast');
insert into marvel_character(id, character_name, affinity) values(1099,'Phil Coulson','Blast');
insert into marvel_character(id, character_name, affinity) values(1100,'Professor X','Blast');
insert into marvel_character(id, character_name, affinity) values(1101,'Psylocke','Blast');
insert into marvel_character(id, character_name, affinity) values(1102,'Rachel Summers','Blast');
insert into marvel_character(id, character_name, affinity) values(1103,'Red Skull','Blast');
insert into marvel_character(id, character_name, affinity) values(1104,'Rescue','Blast');
insert into marvel_character(id, character_name, affinity) values(1105,'Rocket Raccoon','Blast');
insert into marvel_character(id, character_name, affinity) values(1106,'Scarlet Witch','Blast');
insert into marvel_character(id, character_name, affinity) values(1107,'Sister Grimm','Blast');
insert into marvel_character(id, character_name, affinity) values(1108,'Songbird','Blast');
insert into marvel_character(id, character_name, affinity) values(1109,'Star-Lord','Blast');
insert into marvel_character(id, character_name, affinity) values(1110,'Storm','Blast');
insert into marvel_character(id, character_name, affinity) values(1111,'Stryfe','Blast');
insert into marvel_character(id, character_name, affinity) values(1112,'Ulysses Klaue','Blast');
insert into marvel_character(id, character_name, affinity) values(1113,'Vision','Blast');
insert into marvel_character(id, character_name, affinity) values(1114,'Warmachine','Blast');
insert into marvel_character(id, character_name, affinity) values(1115,'Wasp','Blast');
insert into marvel_character(id, character_name, affinity) values(1116,'Wasp (Nadia Van Dyne)','Blast');
insert into marvel_character(id, character_name, affinity) values(1117,'Weapon Hex','Blast');
insert into marvel_character(id, character_name, affinity) values(1118,'Whiplash','Blast');
insert into marvel_character(id, character_name, affinity) values(1119,'Wiccan','Blast');
insert into marvel_character(id, character_name, affinity) values(1120,'Yellowjacket','Blast');
insert into marvel_character(id, character_name, affinity) values(1121,'Aero','Speed');
insert into marvel_character(id, character_name, affinity) values(1122,'Agent 13','Speed');
insert into marvel_character(id, character_name, affinity) values(1123,'Angel','Speed');
insert into marvel_character(id, character_name, affinity) values(1124,'Ant-Man','Speed');
insert into marvel_character(id, character_name, affinity) values(1125,'Arachknight','Speed');
insert into marvel_character(id, character_name, affinity) values(1126,'Baron Zemo','Speed');
insert into marvel_character(id, character_name, affinity) values(1127,'Black Cat','Speed');
insert into marvel_character(id, character_name, affinity) values(1128,'Black Widow','Speed');
insert into marvel_character(id, character_name, affinity) values(1129,'Daredevil','Speed');
insert into marvel_character(id, character_name, affinity) values(1130,'Deadpool','Speed');
insert into marvel_character(id, character_name, affinity) values(1131,'Domino','Speed');
insert into marvel_character(id, character_name, affinity) values(1132,'Electro','Speed');
insert into marvel_character(id, character_name, affinity) values(1133,'Elektra','Speed');
insert into marvel_character(id, character_name, affinity) values(1134,'Elsa Bloodstone','Speed');
insert into marvel_character(id, character_name, affinity) values(1135,'Falcon','Speed');
insert into marvel_character(id, character_name, affinity) values(1136,'Fandral','Speed');
insert into marvel_character(id, character_name, affinity) values(1137,'Fantomex','Speed');
insert into marvel_character(id, character_name, affinity) values(1138,'Gamora','Speed');
insert into marvel_character(id, character_name, affinity) values(1139,'Ghost','Speed');
insert into marvel_character(id, character_name, affinity) values(1140,'Green Goblin','Speed');
insert into marvel_character(id, character_name, affinity) values(1141,'Gwenpool','Speed');
insert into marvel_character(id, character_name, affinity) values(1142,'Hawkeye','Speed');
insert into marvel_character(id, character_name, affinity) values(1143,'Hawkeye (Kate Bishop)','Speed');
insert into marvel_character(id, character_name, affinity) values(1144,'Hellcat','Speed');
insert into marvel_character(id, character_name, affinity) values(1145,'Karnak','Speed');
insert into marvel_character(id, character_name, affinity) values(1146,'Kid Kaiju','Speed');
insert into marvel_character(id, character_name, affinity) values(1147,'Kitty Pryde','Speed');
insert into marvel_character(id, character_name, affinity) values(1148,'Korath','Speed');
insert into marvel_character(id, character_name, affinity) values(1149,'Kraven The Hunter','Speed');
insert into marvel_character(id, character_name, affinity) values(1150,'Luna Snow','Speed');
insert into marvel_character(id, character_name, affinity) values(1151,'Misty Knight','Speed');
insert into marvel_character(id, character_name, affinity) values(1152,'Mystique','Speed');
insert into marvel_character(id, character_name, affinity) values(1153,'Nick Fury','Speed');
insert into marvel_character(id, character_name, affinity) values(1154,'Nightcrawler','Speed');
insert into marvel_character(id, character_name, affinity) values(1155,'Quicksilver','Speed');
insert into marvel_character(id, character_name, affinity) values(1156,'Rogue','Speed');
insert into marvel_character(id, character_name, affinity) values(1157,'Shuri','Speed');
insert into marvel_character(id, character_name, affinity) values(1158,'Silk','Speed');
insert into marvel_character(id, character_name, affinity) values(1159,'Sin','Speed');
insert into marvel_character(id, character_name, affinity) values(1160,'Spider-Gwen','Speed');
insert into marvel_character(id, character_name, affinity) values(1161,'Spider-Man','Speed');
insert into marvel_character(id, character_name, affinity) values(1162,'Spider-Man (Miles Morales)','Speed');
insert into marvel_character(id, character_name, affinity) values(1163,'Spider-Man 2099','Speed');
insert into marvel_character(id, character_name, affinity) values(1164,'Squirrel Girl','Speed');
insert into marvel_character(id, character_name, affinity) values(1165,'Sun Bird','Speed');
insert into marvel_character(id, character_name, affinity) values(1166,'Viper','Speed');
insert into marvel_character(id, character_name, affinity) values(1167,'Vulture','Speed');
insert into marvel_character(id, character_name, affinity) values(1168,'Wave','Speed');
insert into marvel_character(id, character_name, affinity) values(1169,'White Fox','Speed');
insert into marvel_character(id, character_name, affinity) values(1170,'Winter Soldier','Speed');
insert into marvel_character(id, character_name, affinity) values(1171,'Wong','Speed');
insert into marvel_character(id, character_name, affinity) values(1172,'X-23','Speed');
insert into marvel_character(id, character_name, affinity) values(1173,'Yondu','Speed');
insert into marvel_character(id, character_name, affinity) values(1174,'Angela','Universal');
insert into marvel_character(id, character_name, affinity) values(1175,'Anti-Man','Universal');
insert into marvel_character(id, character_name, affinity) values(1176,'Black Bolt','Universal');
insert into marvel_character(id, character_name, affinity) values(1177,'Black Dwarf','Universal');
insert into marvel_character(id, character_name, affinity) values(1178,'Blue Marvel','Universal');
insert into marvel_character(id, character_name, affinity) values(1179,'Captain Marvel','Universal');
insert into marvel_character(id, character_name, affinity) values(1180,'Clea','Universal');
insert into marvel_character(id, character_name, affinity) values(1181,'Corvus Glaive','Universal');
insert into marvel_character(id, character_name, affinity) values(1182,'Dormammu','Universal');
insert into marvel_character(id, character_name, affinity) values(1183,'Destroyer','Universal');
insert into marvel_character(id, character_name, affinity) values(1184,'Doctor Doom','Universal');
insert into marvel_character(id, character_name, affinity) values(1185,'Doctor Voodoo','Universal');
insert into marvel_character(id, character_name, affinity) values(1186,'Ebony Maw','Universal');
insert into marvel_character(id, character_name, affinity) values(1187,'Ghost Panther','Universal');
insert into marvel_character(id, character_name, affinity) values(1188,'Ghost Rider','Universal');
insert into marvel_character(id, character_name, affinity) values(1189,'Ghost Rider (Robbie Reyes)','Universal');
insert into marvel_character(id, character_name, affinity) values(1190,'Heimdall','Universal');
insert into marvel_character(id, character_name, affinity) values(1191,'Hela','Universal');
insert into marvel_character(id, character_name, affinity) values(1192,'Hellstorm','Universal');
insert into marvel_character(id, character_name, affinity) values(1193,'Hyperion','Universal');
insert into marvel_character(id, character_name, affinity) values(1194,'Iron Hammer','Universal');
insert into marvel_character(id, character_name, affinity) values(1195,'Loki','Universal');
insert into marvel_character(id, character_name, affinity) values(1196,'Medusa','Universal');
insert into marvel_character(id, character_name, affinity) values(1197,'Morgan Le Fay','Universal');
insert into marvel_character(id, character_name, affinity) values(1198,'Nova (Sam Alexander)','Universal');
insert into marvel_character(id, character_name, affinity) values(1199,'Odin','Universal');
insert into marvel_character(id, character_name, affinity) values(1200,'Proxima Midnight','Universal');
insert into marvel_character(id, character_name, affinity) values(1201,'Quasar (Avril Kincaid)','Universal');
insert into marvel_character(id, character_name, affinity) values(1202,'Ronan','Universal');
insert into marvel_character(id, character_name, affinity) values(1203,'Satana','Universal');
insert into marvel_character(id, character_name, affinity) values(1204,'Sentinel','Universal');
insert into marvel_character(id, character_name, affinity) values(1205,'Shadow Shell','Universal');
insert into marvel_character(id, character_name, affinity) values(1206,'Silver Surfer','Universal');
insert into marvel_character(id, character_name, affinity) values(1207,'Singularity','Universal');
insert into marvel_character(id, character_name, affinity) values(1208,'Slapstick','Universal');
insert into marvel_character(id, character_name, affinity) values(1209,'Supergiant','Universal');
insert into marvel_character(id, character_name, affinity) values(1210,'Thanos','Universal');
insert into marvel_character(id, character_name, affinity) values(1211,'Thor','Universal');
insert into marvel_character(id, character_name, affinity) values(1212,'Thor (Jane Foster)','Universal');
insert into marvel_character(id, character_name, affinity) values(1213,'Ultron','Universal');
insert into marvel_character(id, character_name, affinity) values(1214,'Victorious','Universal');
