insert into marvel_character(id, character_name, affinity, gender, side) values(1001,'Captain America','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1002,'Absorbing Man','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1003,'Agent Venom','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1004,'America Chavez','Combat', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1005,'Apocalypse','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1006,'Beast','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1007,'Black Panther','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1008,'Blade','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1009,'Bullseye','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1010,'Carnage','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1011,'Colossus','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1012,'Crescent','Combat', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1013,'Crossbones','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1014,'Deathlok','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1015,'Doctor Octopus','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1016,'Drax','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1017,'Giant-Man','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1018,'Goliath','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1019,'Gorgon','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1020,'Gorilla-Man','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1021,'Groot','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1022,'Hogun','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1023,'Hulk','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1024,'Hulkling','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1025,'Iron Fist','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1026,'Iron Man Mark 44 (Hulkbuster)','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1027,'Jessica Jones','Combat', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1028,'Juggernaut','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1029,'Killmonger','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1030,'Kingpin','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1031,'Lizard','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1032,'Luke Cage','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1033,'Minn-Erva','Combat', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1034,'Molten Man','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1035,'Moon Knight','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1036,'Mister Fantastic','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1037,'Ms. Marvel (Kamala Khan)','Combat', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1038,'Namor','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1039,'Nebula','Combat', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1040,'Punisher','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1041,'Red Hulk','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1042,'Rhino','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1043,'Sabretooth','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1044,'Sandman','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1045,'Shang-Chi','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1046,'She-Hulk','Combat', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1047,'Sif','Combat', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1048,'Skurge','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1049,'Sword Master','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1050,'Taskmaster','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1051,'Thing','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1052,'Titania','Combat', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1053,'Ulik','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1054,'Valkyrie','Combat', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1055,'Venom','Combat', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1056,'Volstagg','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1057,'War Tiger','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1058,'Warpath','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1059,'Warwolf','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1060,'White Tiger','Combat', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1061,'Wolverine','Combat', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1062,'Adam Warlock','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1063,'Ancient One','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1064,'Baron Mordo','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1065,'Bisop','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1066,'Blue Dragon','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1067,'Cable','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1068,'Captain America (Sharon Rogers)','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1069,'Crystal','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1070,'Cyclops','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1071,'Daisy Johnson','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1072,'Doctor Strange','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1073,'Emma Frost','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1074,'Enchantress','Blast', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1075,'Gambit','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1076,'Human Torch','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1077,'Hydro-Man','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1078,'Iceman','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1079,'Inferno','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1080,'Invisible Woman','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1081,'Iron Man','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1082,'Ironheart','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1083,'Jean Grey','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1084,'Jubilee','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1085,'Kaecilius','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1086,'Kid Omega','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1087,'Lash','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1088,'Lincoln Campbell','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1089,'M.O.D.O.K.','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1090,'Magik','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1091,'Magneto','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1092,'Malekith','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1093,'Mantis','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1094,'Maximus','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1095,'Mister Sinister','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1096,'Moon Girl','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1097,'Mysterio','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1098,'Negasonic Teenage Warhead','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1099,'Phil Coulson','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1100,'Professor X','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1101,'Psylocke','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1102,'Rachel Summers','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1103,'Red Skull','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1104,'Rescue','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1105,'Rocket Raccoon','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1106,'Scarlet Witch','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1107,'Sister Grimm','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1108,'Songbird','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1109,'Star-Lord','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1110,'Storm','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1111,'Stryfe','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1112,'Ulysses Klaue','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1113,'Vision','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1114,'Warmachine','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1115,'Wasp','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1116,'Wasp (Nadia Van Dyne)','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1117,'Weapon Hex','Blast', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1118,'Whiplash','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1119,'Wiccan','Blast', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1120,'Yellowjacket','Blast', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1121,'Aero','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1122,'Agent 13','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1123,'Angel','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1124,'Ant-Man','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1125,'Arachknight','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1126,'Baron Zemo','Speed', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1127,'Black Cat','Speed', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1128,'Black Widow','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1129,'Daredevil','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1130,'Deadpool','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1131,'Domino','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1132,'Electro','Speed', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1133,'Elektra','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1134,'Elsa Bloodstone','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1135,'Falcon','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1136,'Fandral','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1137,'Fantomex','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1138,'Gamora','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1139,'Ghost','Speed', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1140,'Green Goblin','Speed', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1141,'Gwenpool','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1142,'Hawkeye','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1143,'Hawkeye (Kate Bishop)','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1144,'Hellcat','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1145,'Karnak','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1146,'Kid Kaiju','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1147,'Kitty Pryde','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1148,'Korath','Speed', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1149,'Kraven The Hunter','Speed', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1150,'Luna Snow','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1151,'Misty Knight','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1152,'Mystique','Speed', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1153,'Nick Fury','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1154,'Nightcrawler','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1155,'Quicksilver','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1156,'Rogue','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1157,'Shuri','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1158,'Silk','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1159,'Sin','Speed', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1160,'Spider-Gwen','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1161,'Spider-Man','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1162,'Spider-Man (Miles Morales)','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1163,'Spider-Man 2099','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1164,'Squirrel Girl','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1165,'Sun Bird','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1166,'Viper','Speed', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1167,'Vulture','Speed', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1168,'Wave','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1169,'White Fox','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1170,'Winter Soldier','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1171,'Wong','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1172,'X-23','Speed', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1173,'Yondu','Speed', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1174,'Angela','Universal', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1175,'Anti-Man','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1176,'Black Bolt','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1177,'Black Dwarf','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1178,'Blue Marvel','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1179,'Captain Marvel','Universal', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1180,'Clea','Universal', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1181,'Corvus Glaive','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1182,'Dormammu','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1183,'Destroyer','Universal', 'neutral', 'neutral');
insert into marvel_character(id, character_name, affinity, gender, side) values(1184,'Doctor Doom','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1185,'Doctor Voodoo','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1186,'Ebony Maw','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1187,'Ghost Panther','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1188,'Ghost Rider','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1189,'Ghost Rider (Robbie Reyes)','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1190,'Heimdall','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1191,'Hela','Universal', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1192,'Hellstorm','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1193,'Hyperion','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1194,'Iron Hammer','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1195,'Loki','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1196,'Medusa','Universal', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1197,'Morgan Le Fay','Universal', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1198,'Nova (Sam Alexander)','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1199,'Odin','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1200,'Proxima Midnight','Universal', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1201,'Quasar (Avril Kincaid)','Universal', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1202,'Ronan','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1203,'Satana','Universal', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1204,'Sentinel','Universal', 'neutral', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1205,'Shadow Shell','Universal', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1206,'Silver Surfer','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1207,'Singularity','Universal', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1208,'Slapstick','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1209,'Supergiant','Universal', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1210,'Thanos','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1211,'Thor','Universal', 'male', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1212,'Thor (Jane Foster)','Universal', 'female', 'super hero');
insert into marvel_character(id, character_name, affinity, gender, side) values(1213,'Ultron','Universal', 'male', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1214,'Victorious','Universal', 'female', 'super villain');
insert into marvel_character(id, character_name, affinity, gender, side) values(1215,'Mockingbird','Speed', 'female', 'super hero');
